name: R-pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: "true"        
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install minimal deps
        run: |
          Rscript -e 'install.packages(c("testthat","targets","survival"))'

      - name: Source R/ and run tests
        run: |
          Rscript -e 'fs <- list.files("R", pattern="\\\\.R$", full.names=TRUE); for (f in fs) source(f, chdir=TRUE); if (dir.exists("tests/testthat")) testthat::test_dir("tests/testthat", reporter="summary") else message("no tests dir; skipping")'

