name: R-pipeline

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2   # restores from renv.lock
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev libssl-dev libxml2-dev \
            libharfbuzz-dev libfribidi-dev libcairo2-dev \
            libgl1-mesa-dev libglpk-dev jags
      - name: Run tests
        run: |
          Rscript -e 'if (dir.exists("tests/testthat")) testthat::test_dir("tests/testthat", reporter="summary") else message("no tests directory; skipping")'
